version: '3.8'
services:
    db:
        image: postgres
        restart: always
        container_name: "postgresql"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: shop
        volumes:
            - ./data:/var/lib/postgresql/data 
        ports:
            - "5432:5432"