version: '3.8'
services:
    db:
        image: postgres
        restart: always
        container_name: "postgresql"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: shop
        volumes:
            - ./data:/var/lib/postgresql/data 
        ports:
            - "5432:5432"

    
    rabbitmq:
        image: rabbitmq:3.10.25-management
        hostname: rabbitmq
        restart: always
        ports:
        - "5672:5672"
        - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: mquser
            RABBITMQ_DEFAULT_PASS: mqpassword